version: "3"

services:
  app:
    image: goworkers:worker
    ports:
      - "8081:8081"
    networks:
      - front-tier
      - back-tier
    links:
      - redis
    environment:
      REDIS_URL: redis:6379
  workers:
    image: goworkers:worker
    networks:
      - front-tier
      - back-tier
    links:
      - redis
    environment:
      REDIS_URL: redis:6379
      IS_WORKER: "true"
      NUM_WORKERS: 9

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
